import { Atom, Dna, FlaskConical, Sigma, BookOpen, Landmark, Scale, Globe, Book, Library, Folder, FileText, Calculator, PenSquare, Code, Palette, Music, BrainCircuit, Swords, Puzzle, ClipboardList, MessageSquare, Users, Bot, Send, FileQuestion, BookCheck, Menu, Gavel, Gift, HelpCircle, History, LogOut, Trophy, Home, BookUser, Printer, ShoppingCart } from "lucide-react";

export const iconMap: { [key: string]: React.FC<any> } = {
  Atom,
  Dna,
  FlaskConical,
  Sigma,
  BookOpen,
  Landmark,
  Scale,
  Globe,
  Book,
  Library,
  Folder,
  FileText,
  Calculator,
  PenSquare,
  Code,
  Palette,
  Music,
  BrainCircuit,
  Swords,
  Puzzle,
  ClipboardList,
  MessageSquare,
  Users,
  Bot,
  Send,
  FileQuestion,
  BookCheck,
  Menu,
  Gavel,
  Gift,
  HelpCircle,
  History,
  LogOut,
  Trophy,
  Home,
  BookUser,
  Printer,
  ShoppingCart,
};

export const iconNames = Object.keys(iconMap).sort();
